<!DOCTYPE html>
<html>
<head>
    <title>New Booking Request - {{ $senderName }}</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #f8f9fa; padding: 20px; text-align: center; border-radius: 5px; }
        .content { padding: 20px 0; }
        .section { background: #f9f9f9; padding: 15px; border-radius: 5px; margin: 15px 0; }
        .footer { margin-top: 30px; padding: 20px 0; border-top: 1px solid #f0f0f0; font-size: 14px; color: #666; }
        .calculation { background: #e9f7ef; padding: 15px; border-radius: 5px; margin: 15px 0; border-left: 4px solid #28a745; }
    </style>
</head>
<body>
<div class="header">
    <h1>New Booking Request - {{ $senderName }}</h1>
    <p>Date: {{ now()->format('F j, Y \a\t g:i A') }}</p>
</div>

<div class="content">
    <div class="section">
        <h2>Customer Information</h2>
        <p><strong>Name:</strong> {{ $booking->customer_name }}</p>
        <?php
        // Define the subject line
        $subject = "Reply regarding your booking";
        // URL-encode the subject
        $encoded_subject = urlencode($subject);
        ?>
        <p>
            <strong>Reply to:</strong>
            <a href="mailto:{{ $booking->customer_email }}?subject=<?php echo $encoded_subject; ?>">
                {{ $booking->customer_email }}
            </a>
        </p>
        <?php
        // Simple way to clean the number for the 'tel:' link
        $clean_phone = preg_replace('/[^0-9+]/', '', $booking->customer_phone);
        ?>
        <p>
            <strong>Or call:</strong>
            <a href="tel:<?php echo $clean_phone; ?>">
                {{ $booking->customer_phone }}
            </a>
        </p>
    </div>

    <div class="section">
        <h2>Booking Details</h2>
        <p><strong>Room :</strong> {{ $room->category->name }}</p>
        <p><strong>Check-in:</strong> {{ \Carbon\Carbon::parse($booking->check_in)->format('F j, Y') }}</p>
        <p><strong>Check-out:</strong> {{ \Carbon\Carbon::parse($booking->check_out)->format('F j, Y') }}</p>
        <p><strong>Guests:</strong> {{ $booking->adults }} adults, {{ $booking->children }} children</p>
    </div>

    <div class="calculation">
        <h2>Booking Calculation</h2>
        <p><strong>Duration:</strong> {{ $nights }} nights</p>
        <p><strong>Price per Night:</strong> ₦{{ number_format($room->price_per_night, 2) }}</p>
        <p><strong>Calculation:</strong> {{ $nights }} nights × ₦{{ number_format($room->price_per_night, 2) }}</p>
        <p><strong>Total Amount:</strong> ₦{{ number_format($booking->total_amount, 2) }}</p>
    </div>

    <div class="section">
        <h2>Status & Action Required</h2>
        <p><strong>Status:</strong> {{ ucfirst($booking->status) }}</p>
        <p>Please contact the customer to provide payment details and confirm this booking.</p>
        <?php
        // Define the subject line
        $subject = "Reply regarding your booking";
        // URL-encode the subject
        $encoded_subject = urlencode($subject);
        ?>
        <p>
            <strong>Reply to:</strong>
            <a href="mailto:{{ $booking->customer_email }}?subject=<?php echo $encoded_subject; ?>">
                {{ $booking->customer_email }}
            </a>
        </p>
        <?php
        // Simple way to clean the number for the 'tel:' link
        $clean_phone = preg_replace('/[^0-9+]/', '', $booking->customer_phone);
        ?>
        <p>
            <strong>Or call:</strong>
            <a href="tel:<?php echo $clean_phone; ?>">
                {{ $booking->customer_phone }}
            </a>
        </p>
    </div>
</div>

<div class="footer">
    <p>This email was automatically generated by the booking system.</p>
    <p>Booking ID: {{ $booking->id }}</p>
</div>
</body>
</html>
